{{- if .Values.jobs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jobs
data:
  {{- range .Values.jobs.configs }}
  {{- $job := base (dir .) }}
  {{ $job }}.config.xml: |
    {{- $.Files.Get . | nindent 4 }}
  {{- end }}
{{- end }}
