apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
    - name: master
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
    - name: slave
      port: {{ .Values.service.jnlpPort }}
      targetPort: {{ .Values.service.jnlpPort }}
  selector:
    app: {{ .Values.service.name }}
